---
title: "CN_cleaning"
author: "Jenny Bower"
date: "5/6/2021"
output: html_document
---

```{r}
library(readxl)
library(tidyverse)

```

Import the data.
```{r}
data <- read_excel("data/processed/CN.xlsx", sheet = "Sheet1")
horizons <- read_excel(paste0("data/raw/hb_pedons_analysis_0426.xlsx"))

```

The below subsets the data to samples, and adds columns that calculate organic matter (OM) from carbon data as a percent, and a proportion, as well as calculating bulk density from Federer et al. (1993).
```{r}
sub <- subset(data, type == "sample")
added <- cbind(sub, horizon_id = paste0(sub$pedon,"_",sub$horizon), om_pct = sub$C_pct*1.724, om = (sub$C_pct*1.724)/100, bd = (0.111*1.45)/((1.45*(sub$C_pct*1.724)/100)+((1-(sub$C_pct*1.724)/100)*0.111)))

```

Now we can link it to the main horizon database and all 111 records should merge (except 4--D2, and the three deep glacial till samples).
```{r}
horizonsadded <- cbind(horizons, name = paste0(horizons$pedon,"_",horizons$horizon))
join <- inner_join(horizonsadded, added, by = c("name"="horizon_id"))
write_csv(join, "data/processed/CN_analysis.csv")

#the below script could be used to classify humods, but it doesn't catch pedons that were incrementally sampled (can always modify if needed)
#humod <- cbind(join, humod = "")
#for(a in seq(1:nrow(humod))){
#  if((startsWith(humod$orig_horizon[a], "B")) & (humod$thick[a] > 10) & (humod$C_pct[a] > 6)){
#    humod$humod[a] <- "y"
#  }
#  else{
#    humod$humod[a] <- "n"
#  }
#}
#(startsWith(humod$orig_horizon[a], "B")) && (humod$thick[a] > 10) && (humod$C_pct[a] > 6)

```