---
title: "Extractable cations: Cleaning raw data"
author: "Amanda Pennino"
date: "4/22/2021"
output: html_document
---
```{r}
library(readxl)
library(tidyverse)

```


```{r}
DATA <- read_excel("data/raw/HB_MM_extractablecations_raw.xlsx", sheet = "Conc. in Sample Units")

```

```{r}
#replace below detection limits with NAs
#DATA[DATA == "-99.99"] <- NA

#isolate blanks, remove outliers, find the mean
BLANKS <-subset(DATA, ID == "Blank")

BLANKS <- BLANKS[-2,]

BLANKS <- BLANKS %>%
  summarise_at(.vars = vars(Ca_mgL:Mn_mgL), .funs = mean, na.rm =T) 
                   
#subtract blanks from measurements
DATA <- subset(DATA, ID != "Blank")

DATA$Ca_mgL <- DATA$Ca_mgL - BLANKS$Ca_mgL
DATA$P_mgL <- DATA$P_mgL - BLANKS$P_mgL
DATA$K_mgL <- DATA$K_mgL - BLANKS$K_mgL
DATA$Mg_mgL <- DATA$Mg_mgL - BLANKS$Mg_mgL
DATA$Na_mgL <- DATA$Na_mgL - BLANKS$Na_mgL
DATA$Al_mgL <- DATA$Al_mgL - BLANKS$Al_mgL
DATA$Fe_mgL <- DATA$Fe_mgL - BLANKS$Fe_mgL
DATA$Mn_mgL <- DATA$Mn_mgL - BLANKS$Mn_mgL

```
ppm to cmol/kg (same as meq/100g)
```{r}

mgKg_fun<- function(mgL) {
  DATA <- DATA %>% mutate(mgKg = mgL * (20/4) * (1/1000) * 1000)
  return(DATA$mgKg)
}

mgKg <- mgKg_fun(DATA$Ca_mgL)
DATA$Ca_mgKg = mgKg
DATA$Ca_cmolKg <- (DATA$Ca_mgKg/(40.08/2)/10)

mgKg <- mgKg_fun(DATA$Na_mgL)
DATA$Na_mgKg = mgKg
DATA$Na_cmolKg <- (DATA$Na_mgKg/(22.99/1)/10)

mgKg <- mgKg_fun(DATA$Mg_mgL)
DATA$Mg_mgKg = mgKg
DATA$Mg_cmolKg <- (DATA$Mg_mgKg/(24.3/2)/10)

mgKg <- mgKg_fun(DATA$K_mgL)
DATA$K_mgKg = mgKg
DATA$K_cmolKg <- (DATA$K_mgKg/(39.1/1)/10)

mgKg <- mgKg_fun(DATA$Al_mgL)
DATA$Al_mgKg = mgKg
DATA$Al_cmolKg <- (DATA$Al_mgKg/(26.98/3)/10)

mgKg <- mgKg_fun(DATA$P_mgL)
DATA$P_mgKg = mgKg

mgKg <- mgKg_fun(DATA$Fe_mgL)
DATA$Fe_mgKg = mgKg

mgKg <- mgKg_fun(DATA$Mn_mgL)
DATA$Mn_mgKg = mgKg

DATA$CEC_cmolKg <- rowSums(DATA[,c("Ca_cmolKg", "Na_cmolKg", "Mg_cmolKg", "K_cmolKg")], na.rm = TRUE)
```

```{r}

out_dir <- "data/processed"

write_csv(DATA, paste(out_dir, "ExtractableCationsVTExtractionReRun.csv", sep = "/"))
```




