---
title: "Soil database creation"
author: "Amanda Pennino"
date: "4/22/2021"
output: html_document
---

```{r}
library(tidyverse)
library(readxl)

```

Current database
```{r}
DATA <- read_excel("data/raw/hb_pedons_analysis_0426.xlsx", sheet = "horizon data")

#Create unique id
DATA$ID <- paste(DATA$pedon, DATA$horizon)

```


pH in CaCl2
```{r}
pH <- read_excel("data/processed/pH_0.01M_CaCl2.xlsx")

pH$ID <- paste(pH$pedon, pH$horizon)

DATA <- full_join(DATA, pH, by = "ID")
DATA <- DATA %>% select(-c(pH_id, pedon.y, horizon.y, Dilution_pH, Notes, Date))

```


Carbon, Nitrogen
```{r}
CN <- read_excel("data/processed/CN.xlsx")

CN <- subset(CN, type == "sample")

CN$ID <- paste(CN$pedon, CN$horizon)

CN <- CN %>% select(C_pct, N_pct, CNRatio, ID)

DATA <- full_join(DATA, CN, by = "ID")

DATA <- DATA %>% mutate_at(vars(C_pct:CNRatio), funs(round(., 5)))


```

```{r}

Cations <- read_csv("data/processed/ExtractableCations.csv")

#Below detection limit
Cations[,4:20][is.na(Cations[,4:20])] = -9999.999

Cations$ID <- paste(Cations$pedon, Cations$horizon)

Cations <- Cations %>% select(ID, Ca_cmolKg, Na_cmolKg, Mg_cmolKg, K_cmolKg, CEC_cmolKg)

DATA <- full_join(DATA, Cations, by = "ID")

cols <- names(DATA)[29:33]
DATA <- DATA %>% mutate_at(vars(Ca_cmolKg:CEC_cmolKg), funs(round(., 3)))

```



```{r}
out_dir <- "data/processed"

write_csv(DATA, paste(out_dir, "LATWAG_Soil_Database.csv", sep = "/"))

```



